name: test
on:
  push:
jobs:
  build:
    name: go
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go: ['1.17', '1.18']
    steps:
      - name: setup Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{matrix.go}}

      - name: setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_wrapper: false

      - name: checkout
        uses: actions/checkout@v3

      - name: test
        run: make
